      </table>
      <table width="100%" border="0" cellpadding="0" cellspacing="0" align="center">
        <tr>
          <td style="height: 30px; font-size: 8px;">
            &ensp;
          </td>
        </tr>
        <tr>
          <td style="padding:30px 0">
            <table width="580" border="0" cellpadding="0" cellspacing="0" align="center" class="deviceWidth">
              <tr>
                <td>
                  <table border="0" cellpadding="0" cellspacing="0" align="left" class="deviceWidth">
                    <tr>
                      <td style="padding: 0;">
                        <a href="http://gpbwa.org">
                          <img src="http://gpbwa.org/wp-content/uploads/2016/06/GPB_Footer.png" alt="Governor's Prayer Breakfast" border="0" class="deviceWidth" />
                          <!-- Email generated by City Bible Forum {$domain_address} {$domain_phone} -->
                        </a>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
</body>
</html>
